### ISSUE TITLE
Vocal artists

### ISSUE THREAD

**Issue by timprepscius** [demondragong/deathbyai#1]
To add an item to the list, gather the following information:

Name (name): name of the thing that is threatened by AI
All vocal artists, especially pop singers.

Description (description): 1 or 2 sentences on how AI is threatening this thing
Your favorite singer is already pitch corrected, formant modified, super edited- but pretty soon they won't even be singing.  Does Bieber even own his own voice?  I guess we'll see.

Hope (hope): 1 or 2 sentences on why this thing still has a future
Hopefully there are still a few years before a robots replace live shows.

Link (link): link to something related
https://voice.ai/

Type (type): one of: App, Profession or Other
Profession

Conservation status (conservationStatus): "how bad is it" on the [IUCN Red List](https://en.wikipedia.org/wiki/IUCN_Red_List#Categories). One of: ex (Extinct), ew (Extinct in the wild), cr (Critically Endangered), en (Endangered), vu (Vulnerable), nt (Near Threatened)
en

**Comment by demondragong** [comment]
Thank you! Added it with some edits.

**Comment by timprepscius** [comment]
Could you mark it as already completed by the AI?

https://twitter.com/davidguetta/status/1621605376733872129

**Comment by demondragong** [comment]
Wow! I don't know if I'm more amazed by the fake Eminem voice or the fact that David Guetta is still "innovating" at 55.

Anyway, I added the link you shared to Pop Singers and moved their status from Vulnerable to Endangered.

Thank you :)
