### ISSUE TITLE
Programming (computer programming)

### ISSUE THREAD

**Issue by atleta** [demondragong/deathbyai#2]
name: Programming
description: While programmers, just like everybody else, think they are safe, programming actually happens to be the best documented job on the internet. The job with the most training data available online. Yes, it includes Stackoverflow itself. Unsuprisingly, we already have tools that can help progammers and write some of their code. They'll be able to talk to users and stakeholders soon.
hope: We've written more bad code than good and AI learns to write bugs as well. Also, stakeholders need someone to blame when things don't work.
link: https://github.com/features/copilot
type: Profession
conservationStatus: VU

**Comment by demondragong** [comment]
Thank you! Added it with some edits.
